import { User, Card, SessionResult, PeerRank, Achievement, MotivationalQuote } from '../types';

export const initialUser: User = {
  id: 'u-101',
  username: 'Alex Rivers',
  email: 'alex.rivers@cs.edu',
  avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=AlexRivers',
  grade: 'A',
  overallMarks: 88,
  streakDays: 5,
  totalCardsStudied: 124,
  accuracyPct: 88,
  joinedDate: '2026-08-20',
  themePreference: 'dark',
};

export const initialCards: Card[] = [
  {
    id: 'card-1',
    question: 'What is the output of this Python list comprehension?',
    answer: '[0, 4, 16]',
    code_snippet: 'squares = [x**2 for x in range(5) if x % 2 == 0]\nprint(squares)',
    explanation: 'The loop iterates over 0, 1, 2, 3, 4. The filter `x % 2 == 0` accepts 0, 2, and 4. Squaring each yields [0, 4, 16].',
    language: 'Python',
    category: 'Syntax',
    tags: ['python', 'lists', 'comprehension'],
    difficulty: 1.0,
    interval_level: 2,
    next_due: new Date(Date.now() - 3600000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 3).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-2',
    question: 'What does this JavaScript Promise chain log to console?',
    answer: '42',
    code_snippet: 'Promise.resolve(21)\n  .then(val => val * 2)\n  .then(res => console.log(res));',
    explanation: '.then() passes returned values to the subsequent handler in the chain. 21 * 2 equals 42.',
    language: 'JavaScript',
    category: 'Async',
    tags: ['javascript', 'promises', 'async'],
    difficulty: 1.0,
    interval_level: 1,
    next_due: new Date(Date.now() - 7200000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 1,
    correct_count: 2,
  },
  {
    id: 'card-3',
    question: 'In Go, how do you prevent a deadlock when receiving from an unbuffered channel?',
    answer: 'Ensure a goroutine is concurrently sending to the channel, or use a select block with a default case.',
    code_snippet: 'ch := make(chan int)\ngo func() {\n    ch <- 42\n}()\nval := <-ch',
    explanation: 'Unbuffered channel operations block until both sender and receiver are ready simultaneously. Concurrency prevents main thread lock.',
    language: 'Go',
    category: 'Concurrency',
    tags: ['go', 'channels', 'goroutines', 'concurrency'],
    difficulty: 1.5,
    interval_level: 0,
    next_due: new Date(Date.now() - 10000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-4',
    question: 'In Rust, what does the `?` operator do when placed after an expression returning a Result?',
    answer: 'Unwraps the `Ok(val)` on success, or immediately returns early with the `Err(e)` from the enclosing function.',
    code_snippet: 'fn read_username() -> Result<String, io::Error> {\n    let mut s = String::new();\n    File::open("hello.txt")?.read_to_string(&mut s)?;\n    Ok(s)\n}',
    explanation: 'The `?` operator is syntactic sugar for propagation of errors without verbose `match` statements.',
    language: 'Rust',
    category: 'Error Handling',
    tags: ['rust', 'result', 'error-handling', 'memory'],
    difficulty: 1.2,
    interval_level: 1,
    next_due: new Date(Date.now() - 5000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-5',
    question: 'What SQL clause filters rows AFTER an aggregation like GROUP BY is computed?',
    answer: 'HAVING',
    code_snippet: 'SELECT department, AVG(salary) as avg_sal\nFROM employees\nGROUP BY department\nHAVING AVG(salary) > 85000;',
    explanation: 'WHERE filters rows before grouping; HAVING filters the aggregated summary groups.',
    language: 'SQL',
    category: 'Database',
    tags: ['sql', 'group-by', 'having', 'aggregation'],
    difficulty: 1.0,
    interval_level: 3,
    next_due: new Date(Date.now() + 86400000 * 4).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 3).toISOString(),
    wrong_count: 0,
    correct_count: 4,
  },
  {
    id: 'card-6',
    question: 'In TypeScript, what is the difference between `interface` and `type` for declaration merging?',
    answer: 'Interfaces with the same name automatically merge definitions; `type` aliases cannot be re-opened or merged.',
    code_snippet: 'interface Box { height: number; }\ninterface Box { width: number; }\n// Box now requires both height and width!',
    explanation: 'Declaration merging is unique to interfaces, making them ideal for extensible public API contracts.',
    language: 'TypeScript',
    category: 'Types',
    tags: ['typescript', 'interfaces', 'types'],
    difficulty: 1.1,
    interval_level: 1,
    next_due: new Date(Date.now() - 120000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 1,
    correct_count: 2,
  },
  {
    id: 'card-7',
    question: 'What is the time complexity of searching in a Python dictionary or HashSet on average?',
    answer: 'O(1) average time complexity (constant time lookup via hash table).',
    code_snippet: 'user_lookup = {"u1": "Alice", "u2": "Bob"}\nif "u1" in user_lookup:\n    print("Found in O(1) time")',
    explanation: 'Hashing the key computes the bucket index directly. Worst-case is O(N) only when pathological hash collisions occur.',
    language: 'Python',
    category: 'Algorithms',
    tags: ['python', 'hash-tables', 'big-o', 'algorithms'],
    difficulty: 1.0,
    interval_level: 2,
    next_due: new Date(Date.now() - 1000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-8',
    question: 'What is the JavaScript Event Loop order of microtasks vs macrotasks?',
    answer: 'All pending Microtasks (Promises, queueMicrotask) execute immediately after the current sync code, BEFORE any Macrotasks (setTimeout, setInterval).',
    code_snippet: 'console.log(1);\nsetTimeout(() => console.log(2), 0);\nPromise.resolve().then(() => console.log(3));\nconsole.log(4);\n// Output: 1, 4, 3, 2',
    explanation: 'Sync execution completes (1, 4), then the microtask queue clears (3), then the macrotask timer queue executes (2).',
    language: 'JavaScript',
    category: 'Event Loop',
    tags: ['javascript', 'event-loop', 'async', 'microtasks'],
    difficulty: 1.4,
    interval_level: 0,
    next_due: new Date(Date.now() - 60000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
];

export const initialSessions: SessionResult[] = [
  {
    id: 'sess-1',
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    cards_studied: 12,
    correct_count: 11,
    wrong_count: 1,
    accuracy_pct: 92,
    duration_seconds: 185,
    filter_applied: { language: 'Python' },
  },
  {
    id: 'sess-2',
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    cards_studied: 10,
    correct_count: 8,
    wrong_count: 2,
    accuracy_pct: 80,
    duration_seconds: 210,
    filter_applied: { language: 'JavaScript' },
  },
  {
    id: 'sess-3',
    date: new Date(Date.now() - 86400000 * 1).toISOString(),
    cards_studied: 15,
    correct_count: 14,
    wrong_count: 1,
    accuracy_pct: 93,
    duration_seconds: 260,
    filter_applied: { language: 'All' },
  },
];

export const initialLeaderboard: PeerRank[] = [
  {
    id: 'peer-1',
    username: 'Elena Rostova',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Elena',
    overallMarks: 96,
    grade: 'A+',
    cardsStudied: 320,
    streakDays: 14,
    rank: 1,
  },
  {
    id: 'peer-2',
    username: 'Marcus Vance',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Marcus',
    overallMarks: 91,
    grade: 'A',
    cardsStudied: 245,
    streakDays: 8,
    rank: 2,
  },
  {
    id: 'peer-3',
    username: 'Alex Rivers',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=AlexRivers',
    overallMarks: 88,
    grade: 'A',
    cardsStudied: 124,
    streakDays: 5,
    rank: 3,
  },
  {
    id: 'peer-4',
    username: 'Sarah Chen',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Sarah',
    overallMarks: 84,
    grade: 'B+',
    cardsStudied: 110,
    streakDays: 4,
    rank: 4,
  },
  {
    id: 'peer-5',
    username: 'Devon Miles',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Devon',
    overallMarks: 79,
    grade: 'B',
    cardsStudied: 95,
    streakDays: 3,
    rank: 5,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Step',
    description: 'Completed your first flashcard review session',
    icon: '⚡',
    unlocked: true,
    unlockedAt: 'Aug 20, 2026',
  },
  {
    id: 'ach-2',
    title: '5-Day Flame',
    description: 'Maintained an unbroken 5-day study streak',
    icon: '🔥',
    unlocked: true,
    unlockedAt: 'Sep 10, 2026',
  },
  {
    id: 'ach-3',
    title: 'Polyglot Explorer',
    description: 'Mastered cards across 4 different programming languages',
    icon: '🌐',
    unlocked: true,
    unlockedAt: 'Sep 11, 2026',
  },
  {
    id: 'ach-4',
    title: 'Flawless Run',
    description: 'Scored 100% accuracy on a session with 10+ cards',
    icon: '💎',
    unlocked: false,
  },
  {
    id: 'ach-5',
    title: 'Century Master',
    description: 'Studied over 100 flashcards in total',
    icon: '🏆',
    unlocked: true,
    unlockedAt: 'Sep 11, 2026',
  },
  {
    id: 'ach-6',
    title: 'SRS Disciplinarian',
    description: 'Reached Leitner level 4 on 5 unique cards',
    icon: '🧠',
    unlocked: false,
  },
];

// 18 Original Empathetic Motivational Failure Quotes (No real-person quotes or copyrighted text)
export const motivationalQuotes: MotivationalQuote[] = [
  { id: 1, text: "Mistakes are proof that your neural network is backpropagating new patterns. Keep going!" },
  { id: 2, text: "Every senior engineer once struggled with this exact nuance. Reset, breathe, and conquer it." },
  { id: 3, text: "A missed card isn't a failure — it's the exact moment your brain flags where learning must happen." },
  { id: 4, text: "Syntax can be slippery, but deep concepts take root through repeated encounters. You've got this." },
  { id: 5, text: "Spaced repetition was built precisely for this: catch the miss now so you remember it in production." },
  { id: 6, text: "Great coders aren't born with syntax in their blood; they rehearse it until it becomes muscle memory." },
  { id: 7, text: "Every red card today is a green card tomorrow. Trust the Leitner algorithm process!" },
  { id: 8, text: "Compilers fail silently before they succeed. Give yourself the same patience you give your compiler." },
  { id: 9, text: "Take pride in tackling hard problems. Easy problems never build elite problem-solvers." },
  { id: 10, text: "One stumble doesn't define the walk. Re-read the snippet and take another swing." },
  { id: 11, text: "Confusion is the precursor to clarity. Your mind is reorganizing its knowledge right now." },
  { id: 12, text: "Consistency will always outrun raw talent. Keep your streak alive and stay in the arena." },
  { id: 13, text: "You don't need to know everything today — you just need to know more than yesterday." },
  { id: 14, text: "The interval reset is your safety net, not a punishment. It's making sure this concept sticks forever." },
  { id: 15, text: "Even the creators of these languages look up syntax. What matters is understanding the flow." },
  { id: 16, text: "Celebrate the miss: you just identified the exact gap between where you are and where you're heading!" },
  { id: 17, text: "Deep technical intuition is forged in small daily iterations. You're doing the real work." },
  { id: 18, text: "Focus on the logic, not the pressure. You are capable of mastering every single card in this deck." },
];
