import { User, Card, SessionResult, PeerRank, Achievement, MotivationalQuote } from '../types';

export const initialUser: User = {
  id: 'u-101',
  username: 'Alex Rivers',
  email: 'alex.rivers@cs.edu',
  avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=AlexRivers',
  grade: 'A',
  overallMarks: 88,
  streakDays: 5,
  totalCardsStudied: 124,
  accuracyPct: 88,
  joinedDate: '2026-08-20',
  themePreference: 'dark',
};

export const initialCards: Card[] = [
  {
    id: 'card-1',
    question: 'What is the output of this Python list comprehension?',
    answer: '[0, 4, 16]',
    code_snippet: 'squares = [x**2 for x in range(5) if x % 2 == 0]\nprint(squares)',
    explanation: 'The loop iterates over 0, 1, 2, 3, 4. The filter `x % 2 == 0` accepts 0, 2, and 4. Squaring each yields [0, 4, 16].',
    hint: 'Range(5) generates numbers from 0 to 4. Check the modulo filter for even numbers.',
    language: 'Python',
    category: 'Syntax',
    tags: ['python', 'lists', 'comprehension'],
    difficulty: 1.0,
    interval_level: 2,
    next_due: new Date(Date.now() - 3600000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 3).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-2',
    question: 'What does this JavaScript Promise chain log to console?',
    answer: '42',
    code_snippet: 'Promise.resolve(21)\n  .then(val => val * 2)\n  .then(res => console.log(res));',
    explanation: '.then() passes returned values to the subsequent handler in the chain. 21 * 2 equals 42.',
    hint: 'Each .then() receives the value returned by the previous .then() callback.',
    language: 'JavaScript',
    category: 'Async',
    tags: ['javascript', 'promises', 'async'],
    difficulty: 1.0,
    interval_level: 1,
    next_due: new Date(Date.now() - 7200000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 1,
    correct_count: 2,
  },
  {
    id: 'card-3',
    question: 'In Go, how do you prevent a deadlock when receiving from an unbuffered channel?',
    answer: 'Ensure a goroutine is concurrently sending to the channel, or use a select block with a default case.',
    code_snippet: 'ch := make(chan int)\ngo func() {\n    ch <- 42\n}()\nval := <-ch',
    explanation: 'Unbuffered channel operations block until both sender and receiver are ready simultaneously. Concurrency prevents main thread lock.',
    hint: 'Unbuffered channels require synchronous rendezvous between sender and receiver.',
    language: 'Go',
    category: 'Concurrency',
    tags: ['go', 'channels', 'goroutines', 'concurrency'],
    difficulty: 1.5,
    interval_level: 0,
    next_due: new Date(Date.now() - 10000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-4',
    question: 'In Rust, what does the `?` operator do when placed after an expression returning a Result?',
    answer: 'Unwraps the `Ok(val)` on success, or immediately returns early with the `Err(e)` from the enclosing function.',
    code_snippet: 'fn read_username() -> Result<String, io::Error> {\n    let mut s = String::new();\n    File::open("hello.txt")?.read_to_string(&mut s)?;\n    Ok(s)\n}',
    explanation: 'The `?` operator is syntactic sugar for propagation of errors without verbose `match` statements.',
    hint: 'Think of it as an early return if the result is an Err.',
    language: 'Rust',
    category: 'Error Handling',
    tags: ['rust', 'result', 'error-handling', 'memory'],
    difficulty: 1.2,
    interval_level: 1,
    next_due: new Date(Date.now() - 5000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-5',
    question: 'What SQL clause filters rows AFTER an aggregation like GROUP BY is computed?',
    answer: 'HAVING',
    code_snippet: 'SELECT department, AVG(salary) as avg_sal\nFROM employees\nGROUP BY department\nHAVING AVG(salary) > 85000;',
    explanation: 'WHERE filters individual records before grouping; HAVING filters aggregated groups.',
    hint: 'WHERE works row-by-row before GROUP BY; this clause acts on the resulting aggregate groups.',
    language: 'SQL',
    category: 'Database',
    tags: ['sql', 'group-by', 'having', 'aggregation'],
    difficulty: 1.0,
    interval_level: 3,
    next_due: new Date(Date.now() + 86400000 * 4).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 3).toISOString(),
    wrong_count: 0,
    correct_count: 4,
  },
  {
    id: 'card-6',
    question: 'In TypeScript, what is the difference between `interface` and `type` for declaration merging?',
    answer: 'Interfaces with the same name automatically merge definitions; `type` aliases cannot be re-opened or merged.',
    code_snippet: 'interface Box { height: number; }\ninterface Box { width: number; }\n// Box now requires both height and width!',
    explanation: 'Declaration merging is unique to interfaces, making them ideal for extensible public API contracts.',
    hint: 'Which keyword allows defining the same name twice to add properties?',
    language: 'TypeScript',
    category: 'Types',
    tags: ['typescript', 'interfaces', 'types'],
    difficulty: 1.1,
    interval_level: 1,
    next_due: new Date(Date.now() - 120000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 1,
    correct_count: 2,
  },
  {
    id: 'card-7',
    question: 'What is the time complexity of searching in a Python dictionary or HashSet on average?',
    answer: 'O(1) average time complexity (constant time lookup via hash table).',
    code_snippet: 'user_lookup = {"u1": "Alice", "u2": "Bob"}\nif "u1" in user_lookup:\n    print("Found in O(1) time")',
    explanation: 'Hashing the key computes the bucket index directly. Worst-case is O(N) only when pathological hash collisions occur.',
    hint: 'Hash tables allow direct memory addressing via key hash calculation.',
    language: 'Python',
    category: 'Algorithms',
    tags: ['python', 'hash-tables', 'big-o', 'algorithms'],
    difficulty: 1.0,
    interval_level: 2,
    next_due: new Date(Date.now() - 1000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-8',
    question: 'What is the JavaScript Event Loop order of microtasks vs macrotasks?',
    answer: 'All pending Microtasks (Promises, queueMicrotask) execute immediately after the current sync code, BEFORE any Macrotasks (setTimeout, setInterval).',
    code_snippet: 'console.log(1);\nsetTimeout(() => console.log(2), 0);\nPromise.resolve().then(() => console.log(3));\nconsole.log(4);\n// Output: 1, 4, 3, 2',
    explanation: 'Sync execution completes (1, 4), then the microtask queue clears (3), then the macrotask timer queue executes (2).',
    hint: 'Promises go to the microtask queue, which has higher priority than setTimeout.',
    language: 'JavaScript',
    category: 'Event Loop',
    tags: ['javascript', 'event-loop', 'async', 'microtasks'],
    difficulty: 1.4,
    interval_level: 0,
    next_due: new Date(Date.now() - 60000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-9',
    question: 'In React, when does the cleanup function of a `useEffect` hook execute?',
    answer: 'Before the component unmounts, and before re-running the effect on subsequent renders when dependencies change.',
    code_snippet: 'useEffect(() => {\n  const timer = setInterval(tick, 1000);\n  return () => clearInterval(timer);\n}, [tick]);',
    explanation: 'React runs the cleanup function to tear down subscriptions or timers before applying the new effect or unmounting.',
    hint: 'It does not only run on unmount; it also cleans up previous effect cycles.',
    language: 'React',
    category: 'Hooks',
    tags: ['react', 'hooks', 'useeffect', 'cleanup'],
    difficulty: 1.1,
    interval_level: 1,
    next_due: new Date(Date.now() - 180000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 2,
  },
  {
    id: 'card-10',
    question: 'What is the key difference between `useCallback` and `useMemo` in React?',
    answer: '`useCallback(fn, deps)` returns a memoized function instance; `useMemo(() => fn(), deps)` returns the memoized result of calling the function.',
    code_snippet: 'const memoizedCallback = useCallback(() => doSomething(a, b), [a, b]);\nconst memoizedValue = useMemo(() => computeExpensiveValue(a, b), [a, b]);',
    explanation: 'useCallback preserves referential equality of event handlers passed to child components. `useCallback(fn, deps)` is equivalent to `useMemo(() => fn, deps)`.',
    hint: 'One memoizes the function definition itself; the other memoizes the return value.',
    language: 'React',
    category: 'Hooks',
    tags: ['react', 'usecallback', 'usememo', 'performance'],
    difficulty: 1.2,
    interval_level: 1,
    next_due: new Date(Date.now() - 250000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-11',
    question: 'Why should you use `@functools.wraps` when writing a Python decorator?',
    answer: 'To preserve the original function metadata, such as its `__name__`, `__doc__`, and signature.',
    code_snippet: 'from functools import wraps\n\ndef log_call(fn):\n    @wraps(fn)\n    def wrapper(*args, **kwargs):\n        print(f"Calling {fn.__name__}")\n        return fn(*args, **kwargs)\n    return wrapper',
    explanation: 'Without `@wraps`, inspecting the decorated function reveals `wrapper` instead of the original function name and docstring.',
    hint: 'Without it, your function loses its original identity and introspection data.',
    language: 'Python',
    category: 'Decorators',
    tags: ['python', 'decorators', 'functools', 'metaprogramming'],
    difficulty: 1.3,
    interval_level: 0,
    next_due: new Date(Date.now() - 50000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-12',
    question: 'What is the primary memory advantage of a Python generator over returning a list?',
    answer: 'Generators compute items lazily on demand (`yield`) yielding O(1) memory usage, whereas lists allocate memory for all items upfront (O(N)).',
    code_snippet: 'def infinite_sequence():\n    num = 0\n    while True:\n        yield num\n        num += 1',
    explanation: 'Generators produce values one at a time when `__next__()` is called, allowing processing of massive datasets or infinite streams without running out of RAM.',
    hint: 'Think about lazy evaluation vs eager allocation in memory.',
    language: 'Python',
    category: 'Generators',
    tags: ['python', 'generator', 'yield', 'memory'],
    difficulty: 1.0,
    interval_level: 2,
    next_due: new Date(Date.now() - 90000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 3).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-13',
    question: 'What is a JavaScript Closure and how does it enable private state?',
    answer: 'A closure is a function bundled together with references to its surrounding lexical environment, allowing inner functions to access outer scope variables even after the outer function has returned.',
    code_snippet: 'function createCounter() {\n  let count = 0;\n  return {\n    increment: () => ++count,\n    getCount: () => count\n  };\n}\nconst c = createCounter();',
    explanation: 'The inner functions retain a reference to `count` in the enclosing scope, creating private encapsulated state inaccessible from the outside.',
    hint: 'It remembers variables from where it was created, even when executed elsewhere.',
    language: 'JavaScript',
    category: 'Scope',
    tags: ['javascript', 'closures', 'lexical-scope', 'encapsulation'],
    difficulty: 1.2,
    interval_level: 2,
    next_due: new Date(Date.now() - 300000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 2,
  },
  {
    id: 'card-14',
    question: 'What is the practical difference between debouncing and throttling a function in JavaScript?',
    answer: 'Debounce waits until a quiet period has elapsed after the LAST call; Throttle limits execution to at most once every specified time interval.',
    code_snippet: '// Debounce: Search input auto-complete\n// Throttle: Window scroll or resize listener',
    explanation: 'Debounce groups rapid bursts into a single execution at the end (e.g. typing in search). Throttle guarantees periodic execution during continuous events (e.g. 60fps scrolling).',
    hint: 'One waits for user to pause; the other enforces a steady maximum rate.',
    language: 'JavaScript',
    category: 'Performance',
    tags: ['javascript', 'debounce', 'throttle', 'dom'],
    difficulty: 1.3,
    interval_level: 1,
    next_due: new Date(Date.now() - 400000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 1,
    correct_count: 1,
  },
  {
    id: 'card-15',
    question: 'In TypeScript, what is a Discriminated Union and how does it enable exhaustive type checking?',
    answer: 'A union of object types sharing a common literal discriminator property (e.g. `kind` or `status`), allowing TypeScript to narrow types in switch statements and assert exhaustiveness with `never`.',
    code_snippet: 'type Shape =\n  | { kind: "circle"; radius: number }\n  | { kind: "square"; size: number };\n\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case "circle": return Math.PI * s.radius ** 2;\n    case "square": return s.size * s.size;\n    default: const _exhaustive: never = s; return _exhaustive;\n  }\n}',
    explanation: 'The common literal property acts as a discriminant tag. Checking the tag allows TypeScript to automatically narrow down properties in each branch.',
    hint: 'A shared literal key property lets the compiler know exactly which variant you are handling.',
    language: 'TypeScript',
    category: 'Types',
    tags: ['typescript', 'unions', 'type-narrowing', 'discriminated-unions'],
    difficulty: 1.4,
    interval_level: 0,
    next_due: new Date(Date.now() - 15000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-16',
    question: 'In TypeScript, what does the `<T extends Record<string, unknown>>` constraint enforce?',
    answer: 'Enforces that type generic `T` must be an object type with string keys, preventing primitives like `number`, `string`, or `boolean` from being passed.',
    code_snippet: 'function getProperty<T extends Record<string, unknown>, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}',
    explanation: 'Constraints restrict generics to compatible shapes. Combining `extends Record` with `keyof T` guarantees type-safe property lookups.',
    hint: 'It ensures the generic parameter is strictly an object map rather than a primitive.',
    language: 'TypeScript',
    category: 'Generics',
    tags: ['typescript', 'generics', 'constraints', 'keyof'],
    difficulty: 1.3,
    interval_level: 1,
    next_due: new Date(Date.now() - 80000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-17',
    question: 'In React 18 & 19, what does `useTransition()` accomplish for UI responsiveness?',
    answer: 'Marks state updates as non-urgent transitions, keeping high-priority interactions (typing, clicking) responsive while heavy renders occur in the background.',
    code_snippet: 'const [isPending, startTransition] = useTransition();\n\nfunction handleChange(e) {\n  setInputValue(e.target.value); // Urgent: immediate input update\n  startTransition(() => {\n    setSearchQuery(e.target.value); // Low-priority: filtered list update\n  });\n}',
    explanation: 'React can interrupt a non-urgent transition render if higher-priority user input arrives, preventing UI frame freezes.',
    hint: 'It splits urgent user input from heavy background re-renders.',
    language: 'React',
    category: 'Concurrency',
    tags: ['react', 'usetransition', 'concurrency', 'performance'],
    difficulty: 1.4,
    interval_level: 0,
    next_due: new Date(Date.now() - 45000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-18',
    question: 'What is the search time complexity of a balanced Binary Search Tree vs an unbalanced/degraded BST?',
    answer: 'O(log N) for a balanced BST (e.g. AVL, Red-Black Tree); O(N) worst-case for a degraded skewed tree (acting like a linked list).',
    code_snippet: '// Balanced BST:\n//       8\n//     /   \\\n//    4     12   -> Depth = O(log N)\n// Skewed BST: 1 -> 2 -> 3 -> 4 -> Depth = O(N)',
    explanation: 'Halving the search space at each node requires log2(N) steps when balanced. If nodes are inserted in sorted order without balancing, height equals N.',
    hint: 'Think about tree height: balanced halves the tree at each level; degenerate looks like a line.',
    language: 'DSA',
    category: 'Trees',
    tags: ['dsa', 'trees', 'bst', 'complexity', 'algorithms'],
    difficulty: 1.1,
    interval_level: 2,
    next_due: new Date(Date.now() - 500000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 3).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-19',
    question: 'Which two data structures are combined to implement an LRU (Least Recently Used) Cache with O(1) get and put operations?',
    answer: 'A Hash Map (for O(1) key lookup) and a Doubly Linked List (for O(1) node removal and insertion to the head).',
    code_snippet: 'class LRUCache {\n  // Map<Key, Node> -> O(1) lookup\n  // DoublyLinkedList -> O(1) move-to-head & evict tail\n}',
    explanation: 'The hash map maps keys directly to linked list nodes. Moving an accessed node to the most-recent head and popping from the tail takes constant time.',
    hint: 'You need fast lookup by key plus fast insertion and deletion at both ends.',
    language: 'DSA',
    category: 'System Design',
    tags: ['dsa', 'lru-cache', 'hash-map', 'linked-list'],
    difficulty: 1.5,
    interval_level: 1,
    next_due: new Date(Date.now() - 200000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 1,
    correct_count: 1,
  },
  {
    id: 'card-20',
    question: 'How does the Two Pointers technique optimize the Two Sum problem on a SORTED array to O(N) time and O(1) extra space?',
    answer: 'Initialize left pointer at index 0 and right pointer at index N-1. If sum < target, increment left; if sum > target, decrement right; if equal, solution is found.',
    code_snippet: 'def two_sum_sorted(arr, target):\n    l, r = 0, len(arr) - 1\n    while l < r:\n        s = arr[l] + arr[r]\n        if s == target: return (l, r)\n        elif s < target: l += 1\n        else: r -= 1',
    explanation: 'Since the array is sorted, increasing `l` increases the sum, and decreasing `r` decreases the sum. Every step eliminates one possibility without nested loops.',
    hint: 'One pointer starts at the beginning, the other at the end.',
    language: 'DSA',
    category: 'Algorithms',
    tags: ['dsa', 'two-pointers', 'arrays', 'optimization'],
    difficulty: 1.0,
    interval_level: 3,
    next_due: new Date(Date.now() + 86400000 * 2).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 4,
  },
  {
    id: 'card-21',
    question: 'What causes QuickSort to degrade to O(N²) worst-case time complexity, and how is it mitigated in practice?',
    answer: 'Picking the minimum or maximum element as pivot repeatedly (e.g. sorted input with first/last element pivot). Mitigated by Randomized Pivot or Median-of-Three selection.',
    code_snippet: '// Worst case partitions: [0] and [N-1] elements\n// Median of three: median(arr[start], arr[mid], arr[end])',
    explanation: 'Balanced partitioning divides work into two N/2 halves resulting in O(N log N). Degenerate 1 vs N-1 splits yield N steps of N work = O(N²).',
    hint: 'Think about bad pivot choices on already sorted arrays.',
    language: 'DSA',
    category: 'Sorting',
    tags: ['dsa', 'quicksort', 'sorting', 'complexity'],
    difficulty: 1.3,
    interval_level: 1,
    next_due: new Date(Date.now() - 150000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-22',
    question: 'Why does a B-Tree or B+Tree index perform better than a Binary Search Tree for disk-based relational databases (PostgreSQL, MySQL)?',
    answer: 'B-Trees have high fan-out (hundreds of child pointers per node), matching disk block page sizes and minimizing expensive random disk I/O operations.',
    code_snippet: 'CREATE INDEX idx_user_email ON users(email);\n-- B+Tree depth is typically only 3 to 4 levels for millions of records!',
    explanation: 'A BST has height ~20 for 1M records (requiring 20 disk seeks). A B+Tree with fan-out 100 has height 3-4, requiring only 3-4 disk block reads.',
    hint: 'Binary trees have only 2 children; disk storage prefers wide nodes matching block page size.',
    language: 'SQL',
    category: 'Indexes',
    tags: ['sql', 'btree', 'indexes', 'performance', 'database'],
    difficulty: 1.4,
    interval_level: 1,
    next_due: new Date(Date.now() - 75000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-23',
    question: 'In SQL transaction isolation levels, what is a "Dirty Read" vs a "Phantom Read"?',
    answer: 'Dirty Read: Reading uncommitted changes made by another transaction. Phantom Read: A re-query returns newly inserted or deleted rows committed by another transaction.',
    code_snippet: '// READ UNCOMMITTED: Allows Dirty Reads\n// READ COMMITTED: Prevents Dirty Reads\n// REPEATABLE READ: Prevents Non-repeatable Reads\n// SERIALIZABLE: Prevents Phantom Reads',
    explanation: 'Dirty reads happen before commit. Phantom reads occur when range queries encounter new matching records inserted concurrently.',
    hint: 'One reads uncommitted data; the other encounters newly committed rows appearing in a repeated query.',
    language: 'SQL',
    category: 'Transactions',
    tags: ['sql', 'acid', 'isolation-levels', 'transactions'],
    difficulty: 1.5,
    interval_level: 0,
    next_due: new Date(Date.now() - 25000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
  {
    id: 'card-24',
    question: 'In SQL, what is the difference between `RANK()`, `DENSE_RANK()`, and `ROW_NUMBER()` on tie values?',
    answer: '`ROW_NUMBER()` assigns distinct consecutive integers (1, 2, 3); `RANK()` assigns tied ranks and skips subsequent values (1, 2, 2, 4); `DENSE_RANK()` assigns tied ranks without gaps (1, 2, 2, 3).',
    code_snippet: 'SELECT student, score,\n  ROW_NUMBER() OVER (ORDER BY score DESC) as rn,\n  RANK()       OVER (ORDER BY score DESC) as rk,\n  DENSE_RANK() OVER (ORDER BY score DESC) as drk\nFROM exam_results;',
    explanation: 'When values tie, RANK leaves a gap for the tied positions, while DENSE_RANK continues immediately with the next number.',
    hint: 'One skips numbers after ties, one does not skip, and one gives completely unique sequential numbers.',
    language: 'SQL',
    category: 'Window Functions',
    tags: ['sql', 'window-functions', 'rank', 'dense-rank'],
    difficulty: 1.2,
    interval_level: 1,
    next_due: new Date(Date.now() - 95000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 2,
  },
  {
    id: 'card-25',
    question: 'According to the CAP Theorem, why can a distributed system not simultaneously guarantee both Consistency and Availability during a Network Partition (P)?',
    answer: 'If nodes cannot communicate across a partition, you must choose between rejecting requests to ensure consistency (CP) or accepting writes on isolated nodes leading to inconsistent states (AP).',
    code_snippet: '// Network Partition occurs between Node A and Node B:\n// Option 1 (CP): Block writes on B -> Consistent, but Unavailable\n// Option 2 (AP): Allow writes on B -> Available, but Inconsistent',
    explanation: 'Network partitions are inevitable in real distributed physical networks. Therefore, systems must choose between CP (like MongoDB/HBase) or AP (like Cassandra/DynamoDB).',
    hint: 'When nodes cannot communicate, either you stop answering or you allow divergent data.',
    language: 'System Design',
    category: 'Distributed Systems',
    tags: ['system-design', 'cap-theorem', 'distributed-systems', 'architecture'],
    difficulty: 1.3,
    interval_level: 2,
    next_due: new Date(Date.now() - 110000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 2,
  },
  {
    id: 'card-26',
    question: 'How does the Token Bucket algorithm allow bursts of traffic while enforcing a steady rate limit?',
    answer: 'Tokens are added at a constant refill rate up to a max capacity (bucket size). Each request consumes a token; a burst can consume all stored tokens at once before being throttled.',
    code_snippet: 'class TokenBucket:\n    def allow_request(self):\n        self.refill_tokens()\n        if self.tokens >= 1:\n            self.tokens -= 1\n            return True\n        return False',
    explanation: 'Unlike Leaky Bucket which processes at a strictly uniform rate, Token Bucket accommodates bursty client traffic while guaranteeing average rate limits over time.',
    hint: 'Stored tokens accommodate instantaneous bursts; the refill rate bounds sustained traffic.',
    language: 'System Design',
    category: 'Rate Limiting',
    tags: ['system-design', 'rate-limiting', 'token-bucket', 'networking'],
    difficulty: 1.4,
    interval_level: 1,
    next_due: new Date(Date.now() - 65000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-27',
    question: 'What is the Cache-Aside (Lazy Loading) caching pattern and what is its primary weakness?',
    answer: 'The application checks the cache first; on a cache miss, it reads from the DB and writes to the cache. Primary weakness: Initial cache miss penalty (thundering herd) and stale data if DB is updated directly.',
    code_snippet: 'def get_user(uid):\n    user = cache.get(uid)\n    if not user:\n        user = db.query(uid)\n        cache.set(uid, user, ttl=300)\n    return user',
    explanation: 'Cache-Aside only caches what is actively requested, saving cache memory. Cache invalidation on writes is required to avoid serving stale data.',
    hint: 'The application code itself handles fetching from the DB on miss and populating the cache.',
    language: 'System Design',
    category: 'Caching',
    tags: ['system-design', 'caching', 'cache-aside', 'redis'],
    difficulty: 1.2,
    interval_level: 1,
    next_due: new Date(Date.now() - 130000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 2,
  },
  {
    id: 'card-28',
    question: 'What is the primary benefit of Docker Multi-Stage builds in production containers?',
    answer: 'Drastically reduces production image size and enhances security by leaving compilers, build tools, and dev dependencies out of the final runtime image.',
    code_snippet: '# Build stage\nFROM node:20-alpine AS builder\nWORKDIR /app\nRUN npm run build\n\n# Production runtime stage\nFROM nginx:alpine\nCOPY --from=builder /app/dist /usr/share/nginx/html',
    explanation: 'Multi-stage builds allow compiling in a heavy container and copying only the compiled artifacts into a lightweight, hardened minimal container.',
    hint: 'Build in one container, copy only the finished binary/assets to a slim container.',
    language: 'DevOps',
    category: 'Docker',
    tags: ['devops', 'docker', 'containers', 'security', 'optimization'],
    difficulty: 1.1,
    interval_level: 2,
    next_due: new Date(Date.now() - 350000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 2).toISOString(),
    wrong_count: 0,
    correct_count: 3,
  },
  {
    id: 'card-29',
    question: 'What do `*args` and `**kwargs` do in Python function parameters?',
    answer: '`*args` collects arbitrary extra positional arguments as a tuple; `**kwargs` collects arbitrary extra keyword arguments as a dictionary.',
    code_snippet: 'def flexible_function(*args, **kwargs):\n    print(f"Positional: {args}")\n    print(f"Keywords: {kwargs}")\n\nflexible_function(1, 2, status="active", role="admin")',
    explanation: 'They allow functions to accept any number of arguments, commonly used in decorators, subclassing, and generic wrappers.',
    hint: 'One star captures positional tuple; two stars capture keyword dictionary.',
    language: 'Python',
    category: 'Syntax',
    tags: ['python', 'args', 'kwargs', 'functions'],
    difficulty: 1.0,
    interval_level: 3,
    next_due: new Date(Date.now() + 86400000 * 5).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000 * 4).toISOString(),
    wrong_count: 0,
    correct_count: 5,
  },
  {
    id: 'card-30',
    question: 'How does a Python Context Manager (`with` statement) guarantee resource cleanup even if an unhandled exception occurs?',
    answer: 'Python guarantees the context manager\'s `__exit__(exc_type, exc_val, exc_tb)` method is always executed, similar to a `finally` block.',
    code_snippet: 'class ManagedFile:\n    def __init__(self, filename):\n        self.filename = filename\n    def __enter__(self):\n        self.file = open(self.filename, "w")\n        return self.file\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        if self.file:\n            self.file.close()\n        return False  # Do not suppress exceptions',
    explanation: '`__enter__` acquires resources; `__exit__` handles cleanup and can inspect or suppress exceptions by returning `True`.',
    hint: 'The magic method __exit__ always fires when leaving the with block.',
    language: 'Python',
    category: 'Context Managers',
    tags: ['python', 'with', 'context-manager', 'exceptions'],
    difficulty: 1.2,
    interval_level: 2,
    next_due: new Date(Date.now() - 40000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 2,
  },
  {
    id: 'card-31',
    question: 'What is the primary memory advantage of a JavaScript `WeakMap` or `WeakSet` over standard `Map` or `Set`?',
    answer: 'Keys must be objects and are held "weakly", meaning if there are no other references to the object, it can be garbage collected without causing memory leaks.',
    code_snippet: 'let cache = new WeakMap();\nlet user = { id: 42 };\ncache.set(user, "metadata");\nuser = null; // The entry in cache will be automatically garbage collected!',
    explanation: 'Standard Maps hold strong references, preventing garbage collection indefinitely until manual deletion. WeakMaps prevent leaks when associating metadata with DOM elements or objects.',
    hint: 'Objects used as keys do not prevent the garbage collector from freeing them.',
    language: 'JavaScript',
    category: 'Memory',
    tags: ['javascript', 'weakmap', 'garbage-collection', 'memory'],
    difficulty: 1.4,
    interval_level: 1,
    next_due: new Date(Date.now() - 170000).toISOString(),
    last_reviewed: new Date(Date.now() - 86400000).toISOString(),
    wrong_count: 0,
    correct_count: 1,
  },
  {
    id: 'card-32',
    question: 'In message-driven architectures (Kafka, RabbitMQ), why must consumers be designed to be "Idempotent"?',
    answer: 'Distributed message brokers typically provide "at-least-once" delivery, meaning network retries can deliver the exact same message more than once. Idempotent consumers guarantee identical outcomes regardless of duplicate processing.',
    code_snippet: '// Non-idempotent: account.balance += 50\n// Idempotent: if (!processedMessages.has(msgId)) {\n//   account.balance += 50; processedMessages.add(msgId);\n// }',
    explanation: 'Network timeouts between broker and consumer acknowledgment lead to duplicate message redelivery. Processing duplicate messages must not duplicate business state changes.',
    hint: 'Processing the exact same message multiple times should produce the same result as processing it once.',
    language: 'System Design',
    category: 'Messaging',
    tags: ['system-design', 'kafka', 'idempotency', 'message-queues'],
    difficulty: 1.4,
    interval_level: 0,
    next_due: new Date(Date.now() - 12000).toISOString(),
    last_reviewed: null,
    wrong_count: 0,
    correct_count: 0,
  },
];

export const initialSessions: SessionResult[] = [
  {
    id: 'sess-1',
    date: new Date(Date.now() - 86400000 * 3).toISOString(),
    cards_studied: 12,
    correct_count: 11,
    wrong_count: 1,
    accuracy_pct: 92,
    duration_seconds: 185,
    filter_applied: { language: 'Python' },
  },
  {
    id: 'sess-2',
    date: new Date(Date.now() - 86400000 * 2).toISOString(),
    cards_studied: 10,
    correct_count: 8,
    wrong_count: 2,
    accuracy_pct: 80,
    duration_seconds: 210,
    filter_applied: { language: 'JavaScript' },
  },
  {
    id: 'sess-3',
    date: new Date(Date.now() - 86400000 * 1).toISOString(),
    cards_studied: 15,
    correct_count: 14,
    wrong_count: 1,
    accuracy_pct: 93,
    duration_seconds: 260,
    filter_applied: { language: 'All' },
  },
];

export const initialLeaderboard: PeerRank[] = [
  {
    id: 'peer-1',
    username: 'Elena Rostova',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Elena',
    overallMarks: 96,
    grade: 'A+',
    cardsStudied: 320,
    streakDays: 14,
    rank: 1,
  },
  {
    id: 'peer-2',
    username: 'Marcus Vance',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Marcus',
    overallMarks: 91,
    grade: 'A',
    cardsStudied: 245,
    streakDays: 8,
    rank: 2,
  },
  {
    id: 'peer-3',
    username: 'Alex Rivers',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=AlexRivers',
    overallMarks: 88,
    grade: 'A',
    cardsStudied: 124,
    streakDays: 5,
    rank: 3,
  },
  {
    id: 'peer-4',
    username: 'Sarah Chen',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Sarah',
    overallMarks: 84,
    grade: 'B+',
    cardsStudied: 110,
    streakDays: 4,
    rank: 4,
  },
  {
    id: 'peer-5',
    username: 'Devon Miles',
    avatarUrl: 'https://api.dicebear.com/7.x/bottts/svg?seed=Devon',
    overallMarks: 79,
    grade: 'B',
    cardsStudied: 95,
    streakDays: 3,
    rank: 5,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Step',
    description: 'Completed your first flashcard review session',
    icon: '⚡',
    unlocked: true,
    unlockedAt: 'Aug 20, 2026',
  },
  {
    id: 'ach-2',
    title: '5-Day Flame',
    description: 'Maintained an unbroken 5-day study streak',
    icon: '🔥',
    unlocked: true,
    unlockedAt: 'Sep 10, 2026',
  },
  {
    id: 'ach-3',
    title: 'Polyglot Explorer',
    description: 'Mastered cards across 4 different programming languages',
    icon: '🌐',
    unlocked: true,
    unlockedAt: 'Sep 11, 2026',
  },
  {
    id: 'ach-4',
    title: 'Flawless Run',
    description: 'Scored 100% accuracy on a session with 10+ cards',
    icon: '💎',
    unlocked: false,
  },
  {
    id: 'ach-5',
    title: 'Century Master',
    description: 'Studied over 100 flashcards in total',
    icon: '🏆',
    unlocked: true,
    unlockedAt: 'Sep 11, 2026',
  },
  {
    id: 'ach-6',
    title: 'SRS Disciplinarian',
    description: 'Reached Leitner level 4 on 5 unique cards',
    icon: '🧠',
    unlocked: false,
  },
];

// 18 Original Empathetic Motivational Failure Quotes (No real-person quotes or copyrighted text)
export const motivationalQuotes: MotivationalQuote[] = [
  { id: 1, text: "Mistakes are proof that your neural network is backpropagating new patterns. Keep going!" },
  { id: 2, text: "Every senior engineer once struggled with this exact nuance. Reset, breathe, and conquer it." },
  { id: 3, text: "A missed card isn't a failure — it's the exact moment your brain flags where learning must happen." },
  { id: 4, text: "Syntax can be slippery, but deep concepts take root through repeated encounters. You've got this." },
  { id: 5, text: "Spaced repetition was built precisely for this: catch the miss now so you remember it in production." },
  { id: 6, text: "Great coders aren't born with syntax in their blood; they rehearse it until it becomes muscle memory." },
  { id: 7, text: "Every red card today is a green card tomorrow. Trust the Leitner algorithm process!" },
  { id: 8, text: "Compilers fail silently before they succeed. Give yourself the same patience you give your compiler." },
  { id: 9, text: "Take pride in tackling hard problems. Easy problems never build elite problem-solvers." },
  { id: 10, text: "One stumble doesn't define the walk. Re-read the snippet and take another swing." },
  { id: 11, text: "Confusion is the precursor to clarity. Your mind is reorganizing its knowledge right now." },
  { id: 12, text: "Consistency will always outrun raw talent. Keep your streak alive and stay in the arena." },
  { id: 13, text: "You don't need to know everything today — you just need to know more than yesterday." },
  { id: 14, text: "The interval reset is your safety net, not a punishment. It's making sure this concept sticks forever." },
  { id: 15, text: "Even the creators of these languages look up syntax. What matters is understanding the flow." },
  { id: 16, text: "Celebrate the miss: you just identified the exact gap between where you are and where you're heading!" },
  { id: 17, text: "Deep technical intuition is forged in small daily iterations. You're doing the real work." },
  { id: 18, text: "Focus on the logic, not the pressure. You are capable of mastering every single card in this deck." },
];
